defaults:
  max_rank: 50

items:
  - place_url: "https://map.naver.com/p/entry/place/2051450000"
    keyword: "강남역 맛집"
    place_name: "도원반점 강남역직영점"
  - place_url: "https://map.naver.com/p/entry/place/1476560900"
    keyword: "홍대 카페"
    place_name: "언플러그드 라운지"
